apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mubashertudazvotingapp 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mubashertudazvotingapp 
    spec:
      containers:
        - name: mubashertudazvotingapp 
          image: mmzacr.azurecr.io/mubashertudazvotingapp
          ports:
          - containerPort: 80
